# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1urs3F-oRhu1gG7Yali9vEdlcHVlnidhp
"""

menu = """
[d] Depositar
[s] Sacar
[e] Extrato
[q] Sair
=> """

saldo = 0
limite = 500
extrato = ""
contador_saques = 0
LIMITE_SAQUE = 3

while True:
    opcao = input(menu)

    if opcao == "d":
      valor = float(input("Informe o valor do depósito: "))

      if valor > 0:
        saldo += valor
        extrato += f"Depósito: R$ {valor:.2f}\n"

      else:
        print("Operação falhou! O valor informado é inválido.")

    elif opcao == "s":
      valor = float(input("Informe o valor do saque: "))

      if valor > saldo:
        print("Operação falhou! Não há saldo suficiente em sua conta.")

      elif valor > limite:
        print("Operação falhou! O valor solicitado ultrapassa o limite.")

      elif contador_saques >= LIMITE_SAQUE:
        print("Operação falhou! O limite diário de saques foi atingido.")

      elif valor > 0:
        saldo -= valor
        extrato += f"Saque: R$ {valor:.2f}\n"
        contador_saques += 1

      else:
        print("Operação falhou! O valor informado é inválido.")

    elif opcao == "e":
      print("\n************* EXTRATO *************")
      print("Não foram realizadas movimentações" if not extrato else extrato)
      print(f"\nSaldo: R$ {saldo:.2f}")
      print("*************************************")

    elif opcao == "q":
      break

    else:
      print("Operação inválida, por favor selecione uma opção válida.")